services:
  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  api:
    build: .
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8127
    ports:
      - "8127:8127"
    depends_on:
      - redis

  worker:
    build: .
    environment:
      - REDIS_HOST=redis
    command: celery -A celery_worker:celery_app worker --loglevel=info --concurrency=4
    depends_on:
      - redis